// A11y baseline - known WCAG findings tracked for the dev team.
// Generated by scripts/gen-a11y-baseline.py on 2026-09-25 from a 3-pass
// axe-core collection against staging under the same conditions as axe.spec.ts (36 routes).
// Semantics: a violation NODE matching ANY rule below is KNOWN (surfaced as a test
// annotation and report attachment, does not fail the suite). Anything else FAILS -
// this suite is a tripwire for NEW regressions, not a blanket exclusion.
// Targets are the union of observed node selectors across 3 collection passes: the tripwire
// must not flake on known state variants (e.g. async table content). When the app fixes an
// issue, delete its rule; stale rules are harmless.

export type A11yBaselineRule = {
  violation: string;
  routes: string[]; // ['*'] matches every route
  targets: string[]; // ['*'] matches every node; otherwise substring match on canonicalized axe target
  reason: string;
};

export const a11yBaseline: A11yBaselineRule[] = [
  {
    "violation": "color-contrast",
    "routes": [
      "*"
    ],
    "targets": [
      "*"
    ],
    "reason": "Systemic: the app color tokens produce low-contrast text (sidebar/breadcrumb/link/label families); every new widget triggers new nodes, so per-node tracking cannot converge under parallel load. Remove this rule once the design tokens are fixed, then re-collect."
  },
  {
    "violation": "region",
    "routes": [
      "*"
    ],
    "targets": [
      "*"
    ],
    "reason": "Structural: the dashboard shell does not wrap content in landmark regions - treated as ONE known issue instead of per-node tracking. Remove this rule once the shell adds landmark wrappers."
  },
  {
    "violation": "landmark-one-main",
    "routes": [
      "*"
    ],
    "targets": [
      "html"
    ],
    "reason": "Page content is not wrapped in a <main> landmark (structural, single root cause)."
  },
  {
    "violation": "page-has-heading-one",
    "routes": [
      "*"
    ],
    "targets": [
      "html"
    ],
    "reason": "Authenticated pages expose no H1 heading (structural, single root cause)."
  },
  {
    "violation": "button-name",
    "routes": [
      "*"
    ],
    "targets": [
      "*"
    ],
    "reason": "Systemic: icon-only buttons across the app have no accessible name (window controls, inline-styled card buttons, structural div>div>button variants). Remove once the app labels its icon buttons."
  },
  {
    "violation": "aria-progressbar-name",
    "routes": [
      "*"
    ],
    "targets": [
      ".progress-bar"
    ],
    "reason": "Progress bar rendered without an accessible name."
  },
  {
    "violation": "label",
    "routes": [
      "*"
    ],
    "targets": [
      "*"
    ],
    "reason": "Systemic: inputs and switches (avatar uploads, notification toggles) are not associated with labels. Remove once the app adds labeling."
  },
  {
    "violation": "select-name",
    "routes": [
      "*"
    ],
    "targets": [
      "*"
    ],
    "reason": "Systemic: select controls (page size, filters) have no accessible name. Remove once the app labels its selects."
  },
  {
    "violation": "nested-interactive",
    "routes": [
      "/dashboard/service-provider/create"
    ],
    "targets": [
      ".add-service-item-div"
    ],
    "reason": "Interactive control nested inside another interactive element."
  },
  {
    "violation": "link-name",
    "routes": [
      "*"
    ],
    "targets": [
      "*"
    ],
    "reason": "Systemic: icon-only links (floating create buttons, settings entries) have no accessible name. Remove once the app labels its icon links."
  },
  {
    "violation": "empty-heading",
    "routes": [
      "/dashboard/setting/data-protection"
    ],
    "targets": [
      "h2"
    ],
    "reason": "Empty heading element."
  },
  {
    "violation": "image-redundant-alt",
    "routes": [
      "/dashboard/setting"
    ],
    "targets": [
      "img[alt=\"Account\"]",
      "img[alt=\"Administrator & Users\"]",
      "img[alt=\"Password & Security\"]",
      "img[alt=\"Notifications\"]",
      "img[alt=\"Languages\"]",
      "img[alt=\"Restore Factory Settings\"]",
      "img[alt=\"About HausBuddy\"]",
      "img[alt=\"Imprint\"]",
      "img[alt=\"General Terms and Condition\"]",
      "div > div > .text-decoration-none > div > div > img[width=\"20\"][height=\"20\"]"
    ],
    "reason": "Settings menu images repeat their adjacent visible labels in alt text (observed in a deeper-settled collection)."
  },
  {
    "violation": "aria-prohibited-attr",
    "routes": [
      "/dashboard/damage-report/create"
    ],
    "targets": [
      ".tox-statusbar__resize-handle",
      "#tinymce"
    ],
    "reason": "TinyMCE editor internals (resize handle / editor body) carry prohibited ARIA attributes once the editor initializes."
  },
  {
    "violation": "landmark-unique",
    "routes": [
      "/dashboard/damage-report/create"
    ],
    "targets": [
      "#sidebarMenu"
    ],
    "reason": "Duplicate navigation landmarks flagged on the damage-report composer (editor frame adds a second navigation)."
  },
  {
    "violation": "empty-table-header",
    "routes": [
      "/dashboard/data",
      "/dashboard/service-provider"
    ],
    "targets": [
      ".ag-pinned-right-header > .ag-header-row.ag-header-row-column[aria-rowindex=\"1\"] > .ag-header-cell.ag-header-parent-hidden[role=\"columnheader\"]",
      "th"
    ],
    "reason": "ag-grid pinned header renders an empty column header cell."
  }
];

/**
 * Normalize an axe node target (array of selectors, possibly nested for iframes)
 * into a comparable string: flattened, nth-child/nth-of-type stripped,
 * whitespace collapsed, class chains sorted (axe may emit the same element with
 * a different class order between runs).
 */
export function normalizeA11yTarget(target: readonly unknown[]): string {
  const flat = target
    .map((part) => (Array.isArray(part) ? part.join(' >>> ') : String(part)))
    .join(' ');
  return canonicalizeSelector(flat);
}

function canonicalizeSelector(selector: string): string {
  return selector
    .replace(/:nth-child\(\d+\)/g, '')
    .replace(/:nth-of-type\(\d+\)/g, '')
    .replace(/\s+/g, ' ')
    .trim()
    .replace(/(?:\.[A-Za-z0-9_-]+){2,}/g, (chain) =>
      chain
        .split('.')
        .filter(Boolean)
        .sort()
        .map((cls) => `.${cls}`)
        .join(''),
    );
}

export function isKnownA11yViolation(route: string, violation: string, target: readonly unknown[]): boolean {
  const normalized = normalizeA11yTarget(target);
  return a11yBaseline.some((rule) =>
    rule.violation === violation
    && (rule.routes.includes('*') || rule.routes.includes(route))
    && (rule.targets.includes('*') || rule.targets.some((pattern) => normalized.includes(pattern))),
  );
}
