export const germanInformalPatterns = [
  /\bdu\b/i,
  /\bdein(?:e|er|en|em|es)?\b/i,
  /\bdich\b/i,
  /\bdir\b/i,
  /\beuch\b/i,
  /\beuer(?:e|er|en|em|es)?\b/i,
];

export const germanPageExpectations = [
  ['/dashboard/category', 'Übersicht'],
  ['/dashboard/category/draft', 'Entwürfe'],
  ['/dashboard/category/bin', 'Papierkorb'],
  ['/dashboard/tenant', 'Mieter'],
  ['/dashboard/tenant/draft', 'Entwürfe'],
  ['/dashboard/tenant/bin', 'Papierkorb'],
  ['/dashboard/message', 'Posteingang'],
  ['/dashboard/message/sent', 'Gesendet'],
  ['/dashboard/message/draft', 'Entwürfe'],
  ['/dashboard/message/bin', 'Papierkorb'],
  ['/dashboard/damage-report', 'Schäden'],
  ['/dashboard/damage-report/draft', 'Entwürfe'],
  ['/dashboard/damage-report/bin', 'Papierkorb'],
  ['/dashboard/folder-document', 'Dokumente'],
  ['/dashboard/folder-document/draft', 'Entwürfe'],
  ['/dashboard/folder-document/bin', 'Papierkorb'],
  ['/dashboard/service-provider', 'Dienstleister'],
  ['/dashboard/service-provider/draft', 'Entwürfe'],
  ['/dashboard/service-provider/bin', 'Papierkorb'],
  ['/dashboard/data', 'Daten'],
  ['/dashboard/setting', 'Einstellungen'],
  ['/dashboard/setting/account', 'Konto'],
  ['/dashboard/setting/user', 'Administrator'],
  ['/dashboard/setting/password', 'Passwort'],
  ['/dashboard/setting/notification', 'Benachrichtigungen'],
  ['/dashboard/setting/language', 'Sprachen'],
  ['/dashboard/setting/restore-factory', 'Werkseinstellungen'],
  ['/dashboard/setting/about', 'Über HausBuddy'],
  ['/dashboard/setting/imprint', 'Impressum'],
  ['/dashboard/setting/data-protection', 'Datenschutz'],
  ['/dashboard/setting/general-terms-and-condition', 'Allgemeine Geschäftsbedingungen'],
] as const;
